name: Python Simulation CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8' # Specify a Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Pygame often needs additional OS-level dependencies for display, sound, etc.
        # For a headless CI environment, we might need a virtual framebuffer or ensure Pygame is in a headless mode.
        # Add commands to install these dependencies if tests fail due to missing display.
        # For example, on Ubuntu:
        sudo apt-get update
        sudo apt-get install -y python3-tk libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsdl1.2-dev libsmpeg-dev python3-numpy subversion libportmidi-dev ffmpeg libswscale-dev libavformat-dev libavcodec-dev
        # The above list might be excessive, but it covers common Pygame dependencies.

    - name: Run tests
      run: |
        python test_simulation.py
